[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=optional"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "1"
  npm_config_platform = "linux"
  npm_config_arch = "x64"
